version: "2"
plugins:
  duplication:
    enabled: false
  fixme:
    enabled: true
  radon:
    enabled: true
checks:
  argument-count:
    config:
      threshold: 8
exclude_patterns:
  - "docs/source"
