ci:
  autoupdate_commit_msg: "MAINT: update pre-commit hooks"
  autoupdate_schedule: monthly

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-json
  - id: check-yaml
  - id: check-toml
  - id: check-xml
  - id: debug-statements
  - id: mixed-line-ending

- repo: https://github.com/psf/black
  rev: 23.9.1
  hooks:
  - id: black

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 'v0.0.291'
  hooks:
    - id: ruff
      args: [--fix]
