ci:
  autoupdate_commit_msg: "chore: [pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: monthly

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-json
  - id: check-yaml
  - id: check-toml
  - id: check-xml
  - id: debug-statements
  - id: mixed-line-ending

- repo: https://github.com/PyCQA/isort
  rev: 5.9.3
  hooks:
  - id: isort
    args: ["--project=poliastro", "--section-default=THIRDPARTY"]
    files: |
      (?x)(
        ^src/|
        ^tests/
      )

- repo: https://github.com/psf/black
  rev: 21.10b0
  hooks:
  - id: black-jupyter
    files: |
      (?x)(
        ^src/|
        ^tests/
      )
