# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows
# File shamelessly inspired by Astropy

version: 0.13.dev0-{build}

branches:
  only:
    - master
    - 0.3.x
    - 0.4.x
    - 0.5.x
    - 0.6.x
    - 0.7.x
    - 0.8.x
    - 0.9.x
    - 0.10.x
    - 0.11.x
    - 0.12.x

environment:
  matrix:
    - TOXENV: check
      TOXPYTHON: C:\Python36\python.exe
      PYTHON_HOME: C:\Python36
      PYTHON_VERSION: '3.6'
      PYTHON_ARCH: '64'

    - TOXENV: 'py36'
      TOXPYTHON: C:\Python36-x64\python.exe
      PYTHON_HOME: C:\Python36-x64
      PYTHON_VERSION: '3.6'
      PYTHON_ARCH: '64'

    - TOXENV: 'py37'
      TOXPYTHON: C:\Python37-x64\python.exe
      PYTHON_HOME: C:\Python37-x64
      PYTHON_VERSION: '3.7'
      PYTHON_ARCH: '64'

init:
  - ps: echo $env:TOXENV
  - ps: ls C:\Python*

install:
  - "set PYTHON_BIN=C:\\Python36-x64\\python.exe"
  - "set PIP_BIN=C:\\Python36-x64\\Scripts\\pip.exe"

  # Check that we have the expected version of Python
  - "%PYTHON_BIN% --version"

  # Install dependencies

  - "%PYTHON_BIN% -m pip install --upgrade pip"
  - "%PYTHON_BIN% -m pip install -U pytest"
  - "%PIP_BIN% install .[dev] --prefer-binary" # Test installation correctnessinstall:

  - '%TOXPYTHON% --version'
  - '%PYTHON_HOME%\Scripts\pip --version'
  - '%TOXPYTHON% -m pip install tox'
  - '%TOXPYTHON% -m pip install -U pytest'

build: off

test_script:
  - '%WITH_COMPILER% %PYTHON_HOME%\Scripts\tox'
