# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows
# File shamelessly inspired by Astropy

version: 0.13.dev0-{build}

branches:
  only:
    - master
    - 0.3.x
    - 0.4.x
    - 0.5.x
    - 0.6.x
    - 0.7.x
    - 0.8.x
    - 0.9.x
    - 0.10.x
    - 0.11.x
    - 0.12.x

environment:
  matrix:
    - TOXENV: check
      PYTHON: C:\Python36\python.exe

    - TOXENV: 'py36'
      PYTHON: C:\Python36-x64\python.exe

    - TOXENV: 'py37'
      PYTHON: C:\Python37-x64\python.exe

init:
  - ps: echo $env:TOXENV
  - ps: ls C:\Python*

install:
  # Install dependencies
  - '%PYTHON% --version'
  - "%PYTHON% -m pip install --upgrade pip"
  - '%PYTHON% -m pip install tox'

build: off

test_script:
  - '%WITH_COMPILER% %PYTHON% -m tox'
