name: poliastro
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - astropy!=2.0.0
  - jplephem
  - matplotlib
  - numba
  - numpy
  - scipy
  - nbsphinx
  - IPython
  - ipykernel
  - bs4
  - requests
