name: Release
on:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main

jobs:

  release:
    name: Version ${{ github.ref_name }}
    # if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip flit twine
      - name: Build and check distribution files
        run: |
          python -m flit build && python -m twine check dist/*
          ls -a dist/
  #    - name: Publish to PyPI
  #      env:
  #        TWINE_USERNAME: __token__
  #        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
  #      run: |
  #        python -m twine upload --skip-existing ./**/*.whl
  #        python -m twine upload --skip-existing ./**/*.tar.gz
  #    - name: Publish to GitHub
  #      uses: softprops/action-gh-release@v1
  #      with:
  #        files: |
  #          ./dist/*.whl
  #          ./dist/*.tar.gz
